# Generated by Django 4.1.5 on 2023-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ManyToManyField(to='dashboard.job'),
        ),
    ]
